# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_emotion_useremotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
