# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160730_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='infographic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
