# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 15:12
from __future__ import unicode_literals

from django.db import migrations
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160730_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=news.models.SafeHtmlField(default=''),
        ),
    ]
