# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20160730_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='question',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
