# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20160730_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_fb_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
