# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='facebook_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
