# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbmessages', '0002_auto_20160730_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='notification_time',
            field=models.IntegerField(choices=[(7, '7AM'), (12, '12PM'), (15, '3PM')], default=7),
        ),
    ]
