# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='picture',
            field=models.ImageField(upload_to='kids'),
        ),
    ]
